export const aptitudes = {
  // Characteristics
  WEAPON_SKILL: "WEAPON_SKILL",
  BALLISTIC_SKILL: "BALLISTIC_SKILL",
  STRENGTH: "STRENGTH",
  TOUGHNESS: "TOUGHNESS",
  AGILITY: "AGILITY",
  INTELLIGENCE: "INTELLIGENCE",
  PERCEPTION: "PERCEPTION",
  WILLPOWER: "WILLPOWER",
  FELLOWSHIP: "FELLOWSHIP",
  // Other Aptitudes
  OFFENCE: "OFFENCE",
  FINESSE: "FINESSE",
  DEFENSE: "DEFENSE",
  PSYKER: "PSYKER",
  TECH: "TECH",
  KNOWLEDGE: "KNOWLEDGE",
  LEADERSHIP: "LEADERSHIP",
  FIELDCRAFT: "FIELDCRAFT",
  SOCIAL: "SOCIAL"
};

export const roles = {
  ASSASSIN: "ASSASSIN",
  CHIRURGEON: "CHIRURGEON",
  MYSTIC: "MYSTIC"
};
